### ISSUE TITLE
0.3.0 throws an Error in decodeAudioData promise supporting browsers

### ISSUE THREAD

**Issue by odub** [mohayonao/promise-decode-audio-data#8]
Root cause: there's a `require` in the built output JS [here](https://github.com/mohayonao/promise-decode-audio-data/blob/master/build/promise-decode-audio-data.js#L7).

**Comment by odub** [comment]
<img width="677" alt="screen shot 2016-11-16 at 14 48 06" src="https://cloud.githubusercontent.com/assets/1530044/20352276/8f9c446a-ac0e-11e6-81c2-7935d2b86727.png">

**Comment by mohayonao** [comment]
This package works fine in my environments. 
Please tell me the environment that this error occurs.

**Comment by odub** [comment]
Maybe try from a clean `npm install` rather than a development build?

I found the error in Safari and assumed it hit anyone on that side of the `if` statement.

**Comment by mohayonao** [comment]
Does this very tiny example work in your environment?

project
https://gist.github.com/mohayonao/89fd55526cef5a60364e860695a4bf75

bundle source code
https://gist.github.com/mohayonao/d83e196542005240b55569c29ff7e5dd

**Comment by odub** [comment]
Chrome:
![screen shot 2016-11-17 at 12 22 55](https://cloud.githubusercontent.com/assets/1530044/20389261/c2c97ecc-acc0-11e6-901e-33e5359cd1c0.png)

Safari:
![screen shot 2016-11-17 at 12 23 19](https://cloud.githubusercontent.com/assets/1530044/20389265/cac1aa1e-acc0-11e6-8331-7f47a9c1fc6f.png)

**Comment by mohayonao** [comment]
In Safari, what is return value? Safari 10?

```js
Object.getPrototypeOf(webkitOfflineAudioContext)
```

**Comment by odub** [comment]
Hrm, so in Safari 9.1.3, I get `{}`

In Safari 10.0.1:
![screen shot 2016-11-17 at 12 42 37](https://cloud.githubusercontent.com/assets/1530044/20389885/df15530a-acc3-11e6-8984-fda724618901.png)

**Comment by mohayonao** [comment]
okay, I found the cause of this issue.
(In Safari 9, typeof webkitAudioContext is not "function" ...)

I'll fix it, please wait a moment.

**Comment by mohayonao** [comment]
fix this issue at v0.4.0

**Comment by odub** [comment]
Thanks for looking into this
